services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mgnrega-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/mgnrega.db
      - CORS_ORIGINS=http://localhost,http://localhost:80,http://localhost:3000
      - CACHE_EXPIRY_HOURS=24
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mgnrega-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:

